### ISSUE TITLE
Report EPIPE write EPIPE

### ISSUE THREAD

**Issue by yangjunying** [vknabel/vscode-swiftlint#15] opened 2020-04-14 14:51 UTC
`Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:146:25)
	at writeGeneric (internal/stream_base_commons.js:137:3)
	at Socket._writeGeneric (net.js:698:11)
	at Socket._write (net.js:710:8)
	at doWrite (_stream_writable.js:418:12)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at Socket.Writable.end (_stream_writable.js:583:10)
	at Socket.end (net.js:536:31)
	at /Users/junyingyang/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:176:24
	at new Promise (<anonymous>)
	at execSwiftlint (/Users/junyingyang/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:150:12)
	at Object.<anonymous> (/Users/junyingyang/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:27:38)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/junyingyang/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:5:58)`

**Comment by vknabel** [comment] 2020-04-18 15:32
Hi @yangjunying, thanks for your report!
It seems like this issue is a duplicate of #11, but I am very curios about how to reproduce this issue.

Do you still remember when this error happened?
Was there anything special about your local setup?
How big was your project?
Does it include dependencies like CocoaPods or Carthage?
I'd be very glad if you could answer a few questions of these in #11!

Thanks in advance!

**Closed by vknabel** 2020-04-18 15:32 UTC
Labels: duplicate
