### ISSUE TITLE
Report 1 Command failed: /usr/local/bin/swiftlint --use-script-input-files --quiet --reporter json --formatUnrecognized arguments: --format

### ISSUE THREAD

**Issue by jepiqueau** [vknabel/vscode-swiftlint#49] opened 2022-08-31 07:47 UTC
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Flocal%2Fbin%2Fswiftlint%20--use-script-input-files%20--quiet%20--reporter%20json%20--format%0AUnrecognized%20arguments%3A%20--format%0A%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A406%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A390%3A28)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1064%3A16)%0A%20%20%20%20at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A450%3A11)%0A%20%20%20%20at%20Socket.emit%20(node%3Aevents%3A390%3A28)%0A%20%20%20%20at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A687%3A12)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment] 2022-09-05 06:56
Thanks for your feedback. Closing as it's a duplicate of #47

**Closed by vknabel** 2022-09-05 06:56 UTC
