### ISSUE TITLE
Report EPIPE write EPIPE

### ISSUE THREAD

**Issue by jpmoor271** [vknabel/vscode-swiftlint#17] opened 2020-05-07 21:05 UTC
`Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:146:25)
	at writeGeneric (internal/stream_base_commons.js:137:3)
	at Socket._writeGeneric (net.js:698:11)
	at Socket._write (net.js:710:8)
	at doWrite (_stream_writable.js:418:12)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at Socket.Writable.end (_stream_writable.js:583:10)
	at Socket.end (net.js:536:31)
	at /Users/jasonmoore/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:176:24
	at new Promise (<anonymous>)
	at execSwiftlint (/Users/jasonmoore/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:150:12)
	at Object.<anonymous> (/Users/jasonmoore/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:27:38)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/jasonmoore/.vscode/extensions/vknabel.vscode-swiftlint-1.2.2/out/lint.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)`

**Comment by vknabel** [comment] 2020-05-08 09:02
Hi @jpmoor271. Thanks for the report! 

Do you remember when the error happened? How big was the project?
We’re there many SwiftLint warnings/errors?

Does running SwiftLint work on the command line? It seems like it exited too early. 

Could you try to update your SwiftLint in case it is outdated?

**Comment by vknabel** [comment] 2020-06-20 07:12
Duplicate of #11, which provides a workaround:

`sudo xcode-select /Applications/Xcode.app`

**Closed by vknabel** 2020-06-20 07:12 UTC
