### ISSUE TITLE
Report 1 Command failed: /usr/bin/env swiftlint lint --use-script-input-files --quiet --reporter jsonError: No lintable files found at paths: ''

### ISSUE THREAD

**Issue by Qusea** [vknabel/vscode-swiftlint#64] opened 2023-06-13 11:01 UTC
%60Error%3A%20Command%20failed%3A%20%2Fusr%2Fbin%2Fenv%20swiftlint%20lint%20--use-script-input-files%20--quiet%20--reporter%20json%0AError%3A%20No%20lintable%20files%20found%20at%20paths%3A%20''%0A%0A%20%20%20%20at%20ChildProcess.exithandler%20(node%3Achild_process%3A409%3A12)%0A%20%20%20%20at%20ChildProcess.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20maybeClose%20(node%3Ainternal%2Fchild_process%3A1121%3A16)%0A%20%20%20%20at%20Socket.%3Canonymous%3E%20(node%3Ainternal%2Fchild_process%3A479%3A11)%0A%20%20%20%20at%20Socket.emit%20(node%3Aevents%3A513%3A28)%0A%20%20%20%20at%20Pipe.%3Canonymous%3E%20(node%3Anet%3A757%3A14)%0Aos%3A%20darwin%60

**Comment by vknabel** [comment] 2023-06-26 06:39
thanks for you report. Duplicate of #58

**Closed by vknabel** 2023-06-26 06:39 UTC
